"""empty message

Revision ID: 164ec81f70e5
Revises: 51d95d44e924
Create Date: 2025-09-02 23:16:54.524549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164ec81f70e5'
down_revision = '51d95d44e924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('user')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
