"""empty message

Revision ID: 51d95d44e924
Revises: a0a2afa96dc3
Create Date: 2025-09-02 22:32:46.598552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d95d44e924'
down_revision = 'a0a2afa96dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_email_key', type_='unique')
        batch_op.drop_constraint('customers_phone_key', type_='unique')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint('customers_phone_key', ['phone'])
        batch_op.create_unique_constraint('customers_email_key', ['email'])

    # ### end Alembic commands ###
